### ISSUE TITLE
provide a sql migration

### ISSUE THREAD

**Issue by goern** [thoth-station/package-releases-job#234]
provide a sql alchemy migration so that app.py can be run, otherwise (following the readme) if failes with:

```
2019-09-22 12:04:12,042 [11661] CRITICAL root:101: Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "python_package_index" does not exist
LINE 2: FROM python_package_index
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./app.py", line 269, in <module>
    cli()
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./app.py", line 257, in cli
    only_if_package_seen=only_if_package_seen,
  File "./app.py", line 130, in package_releases_update
    sources = [Source(**config) for config in graph.python_package_index_listing()]
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 1079, in python_package_index_listing
    return [{"url": item[0], "warehouse_api_url": item[1], "verify_ssl": item[2]} for item in query.all()]
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3178, in all
    return list(self)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3359, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "python_package_index" does not exist
LINE 2: FROM python_package_index
             ^

[SQL: SELECT python_package_index.url AS python_package_index_url, python_package_index.warehouse_api_url AS python_package_index_warehouse_api_url, python_package_index.verify_ssl AS python_package_index_verify_ssl
FROM python_package_index]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by fridex** [comment]
We should update the README file. Migration logic should be owned by one component in the system (otherwise we will lose control of the current schema version in deployment and components will error out) - other components (like this one) require already initialized database.
