### ISSUE TITLE
Scheduling packages not existing on certain indexes slows down Thoth learning rate

### ISSUE THREAD

**Issue by pacospace** [thoth-station/package-releases-job#609]
**Describe the bug**
Checking lot of pods failing in thoth-middletier-stage because packages release job is scheduling packages that do not exist on certain indexes. This is related to the logic used in packages release which does not take into account package names from the indexes to check package_names but actually considering `PythonPackageVersionEntity table` from Thoth database (https://github.com/thoth-station/package-releases-job/blob/e7f356887ce1fb33fc9847eb60f64432c0469d65/producer.py#L292) without checking any index.

**To Reproduce**
1. run package-release job

**Expected behaviour**
packages not present on certain indexes are not scheduled for solvers.

**Screenshots**
```
2021-10-14 12:18:14,538  13 INFO     thoth.solver.python.python:251: Resolving package 'cloudpickle' with version specifier '===0.4.0' from 'https://download.pytorch.org/whl/cu111'
2021-10-14 12:18:14,933  13 ERROR    thoth.solver.python.python:199: Failed to resolve versions for 'cloudpickle' with version spec '===0.4.0'
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/solver/python/python.py", line 189, in _resolve_versions
    resolved_versions = solver.solve([package_name + (version_spec or "")])
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/solver/python/base.py", line 74, in solve
    name, releases = self.releases_fetcher.fetch_releases(dep.name)
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/solver/python/python_solver.py", line 48, in fetch_releases
    releases = self.source.get_package_versions(package_name)
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/python/source.py", line 250, in get_package_versions
    return self._simple_repository_list_versions(package_name)
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/python/source.py", line 239, in _simple_repository_list_versions
    for artifact_name, _ in self._simple_repository_list_artifacts(package_name):
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/python/source.py", line 302, in _simple_repository_list_artifacts
    response.raise_for_status()
  File "/opt/app-root/lib64/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/cu111/cloudpickle
2021-10-14 12:18:16,132  13 WARNING  thoth.solver.python.python:256: No versions were resolved for dependency 'cloudpickle' in version '===0.4.0'
2021-10-14 12:18:16,541  13 CRITICAL root:105: Traceback (most recent call last):
  File "/opt/app-root/src/thoth/solver/cli.py", line 164, in <module>
    cli()
  File "/opt/app-root/lib64/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/src/thoth/solver/cli.py", line 142, in python
    result = resolve_python(
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/solver/python/python.py", line 410, in resolve
    solver_result = _do_resolve_index(
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/solver/python/python.py", line 261, in _do_resolve_index
    "is_provided_package": source.provides_package(dependency.name),
  File "/opt/app-root/lib64/python3.9/site-packages/thoth/python/source.py", line 209, in provides_package
    response.raise_for_status()
  File "/opt/app-root/lib64/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/cu111/cloudpickle
```

**Additional context**

**Comment by pacospace** [comment]
> @fridex I tried the endpoint on management-api but the record is not updated and no issues are raised.

The other endpoint works, so the problem might be in the logic, that altough it works locally, it does not work in the cluster. I updated the method PTAL: https://github.com/thoth-station/storages/pull/2442/files
